package workflowkit

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/opencharly/sdk/deploykit"
	"github.com/opencharly/sdk/kit"
	"github.com/opencharly/spec/shellquote"
	"github.com/opencharly/spec/spec"
	"gopkg.in/yaml.v3"
)

// lower.go — the ONE lowering from an authored `kind: pipeline` body to the pair an
// engine consumes:
//
//   - the `.lobster` workflow (the engine's own IR), and
//   - a generated `charly.yml`, the charly-side tasks the `charly:` / `plan:` steps
//     invoke (the engine runs `charly -C <gen-dir> task <entity> …`).
//
// The engine owns WHEN the pair is regenerated and WHERE it lives; this file owns WHAT
// it is. All three inputs are DATA (R3): the project dir (for the relative import), the
// generation dir (the file's own directory, its basename is the workflow name), and the
// charly binary path to bake into every `run:`.

// lobsterDrop are the pipeline-level keys owned by the ENGINE, never by the lobster IR:
// `engine` selects the engine itself; `triggers` become a systemd timer (see
// deploykit.GenerateSystemdTimer); `config` is engine config; `entities` are inline
// charly nodes, which belong in the generated charly.yml; `concurrency` is an engine
// scheduling hint.
var lobsterDrop = map[string]bool{
	"concurrency": true,
	"config":      true,
	"entities":    true,
	"triggers":    true,
	"engine":      true,
}

// Lower lowers an authored pipeline into its (lobsterYAML, charlyYAML) pair. It validates
// first, so a lowering never emits a half-valid pair.
//
// The workflow name is the generation directory's basename; every generated charly task is
// named `_pipeline-<name>-<id>`.
func Lower(p *spec.Pipeline, projectDir, genDir, charlyBin string) ([]byte, []byte, error) {
	if err := ValidatePipeline(p); err != nil {
		return nil, nil, err
	}
	name := filepath.Base(filepath.Clean(genDir))

	body, err := marshalNode(p)
	if err != nil {
		return nil, nil, fmt.Errorf("lowering %s: %w", name, err)
	}

	gen := &lowerCtx{name: name, genDir: genDir, charlyBin: charlyBin}
	lobsterSteps := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
	if steps := kit.MappingChild(body, "steps"); steps != nil && steps.Kind == yaml.SequenceNode {
		for i, st := range steps.Content {
			out, lerr := gen.lowerStep(st, fmt.Sprintf("steps[%d]", i))
			if lerr != nil {
				return nil, nil, lerr
			}
			lobsterSteps.Content = append(lobsterSteps.Content, out)
		}
	}

	// the .lobster workflow: `name` first, then every lobster-native pipeline key (the
	// engine-owned ones dropped), then the lowered steps.
	flow := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	setKey(flow, "name", scalarNode(name))
	for i := 0; i+1 < len(body.Content); i += 2 {
		k := body.Content[i].Value
		if lobsterDrop[k] || k == "steps" {
			continue
		}
		flow.Content = append(flow.Content, body.Content[i], body.Content[i+1])
	}
	setKey(flow, "steps", lobsterSteps)

	// the generated charly.yml — the charly-side half.
	if genDir == "" {
		return nil, nil, fmt.Errorf("lowering %s: empty generation dir", name)
	}
	rel, rerr := filepath.Rel(genDir, filepath.Join(projectDir, "charly.yml"))
	if rerr != nil {
		rel = filepath.Join(projectDir, "charly.yml")
	}
	cy := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map", HeadComment: generatedHeader}
	setKey(cy, "import", &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq", Content: []*yaml.Node{scalarNode(rel)}})
	for _, t := range gen.tasks {
		setKey(cy, t.name, t.node)
	}
	if ents := kit.MappingChild(body, "entities"); ents != nil {
		setKey(cy, "entities", ents)
	}

	lobsterYAML, err := yaml.Marshal(flow)
	if err != nil {
		return nil, nil, fmt.Errorf("marshalling the lowered workflow: %w", err)
	}
	charlyYAML, err := yaml.Marshal(cy)
	if err != nil {
		return nil, nil, fmt.Errorf("marshalling the generated charly.yml: %w", err)
	}
	return lobsterYAML, charlyYAML, nil
}

// generatedHeader is the header comment of every generated charly.yml. It records the
// import rule that makes the generated file loadable — the single non-obvious constraint
// in this whole file.
const generatedHeader = `GENERATED by charly's workflow lowering — do not edit; edit the pipeline and re-lower.
The engine runs this file as the ROOT (charly -C <this dir> …), so the import: below is
resolved RELATIVE TO THIS FILE'S OWN DIRECTORY.
It MUST flat-import the project's charly.yml BY FILE PATH: the loader reads a flat
(non-@) import entry straight with os.ReadFile and never joins it against a directory,
so pointing it at a DIRECTORY (e.g. ` + "`../../..`" + `) silently fails to load. Only an
@-namespaced entry is stat'ed and joined with the unified file name — so a file path is
the ONE form that works for a flat import.`

// lowerCtx carries the lowering state: where we generate, which charly binary to bake in,
// and the generated charly tasks collected while walking the steps.
type lowerCtx struct {
	name      string
	genDir    string
	charlyBin string
	tasks     []generatedTask
}

// generatedTask is one `_pipeline-<name>-<id>:` entry of the generated charly.yml.
type generatedTask struct {
	name string
	node *yaml.Node
}

// lowerStep lowers ONE step (or sub-step / parallel branch) in place and returns it. A
// `plan:` step becomes a `run:` that calls the generated charly task with `--output` and
// the step's lobstered references passed as `-p REF_n="$REF_n"`; a `charly:` step becomes a
// `run:` that calls charly with the shell-quoted argv. Every lobster-native key passes
// through untouched.
func (c *lowerCtx) lowerStep(st *yaml.Node, path string) (*yaml.Node, error) {
	if st == nil || st.Kind != yaml.MappingNode {
		return st, nil
	}

	// recurse into the nested step lists FIRST, so a branch's own plan:/charly: lowers too.
	if par := kit.MappingChild(st, "parallel"); par != nil {
		if br := kit.MappingChild(par, "branches"); br != nil && br.Kind == yaml.SequenceNode {
			for i, b := range br.Content {
				out, err := c.lowerStep(b, fmt.Sprintf("%s.parallel.branches[%d]", path, i))
				if err != nil {
					return nil, err
				}
				br.Content[i] = out
			}
		}
	}
	if subs := kit.MappingChild(st, "steps"); subs != nil && subs.Kind == yaml.SequenceNode {
		for i, b := range subs.Content {
			out, err := c.lowerStep(b, fmt.Sprintf("%s.steps[%d]", path, i))
			if err != nil {
				return nil, err
			}
			subs.Content[i] = out
		}
	}

	id := ""
	if v := kit.MappingChild(st, "id"); v != nil {
		id = v.Value
	}
	pruneEmptyMappings(st)

	if plan := kit.MappingChild(st, "plan"); plan != nil && plan.Kind == yaml.SequenceNode {
		planCopy, err := cloneNode(plan)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		// emit the AUTHORED sugar, not the internal plugin/plugin_input pair the loader
		// desugared this plan into (the generated file is re-loaded by the loader).
		deploykit.ResugarPlan(planCopy, nil)
		refs := planRefs(planCopy)
		entity := c.addTask(id, planCopy)

		argv := []string{c.charlyBin, "-C", c.genDir, "task", entity, "--output"}
		if len(refs) > 0 {
			env := ensureMapping(st, "env")
			for i, r := range refs {
				varName := fmt.Sprintf("REF_%d", i+1)
				// lobster resolves the ref into the step's env; the `-p` passes it on to
				// the charly task, where ${REF_n} expands it (see workflowkit.ExpandVars).
				setKey(env, varName, scalarNode(r))
				argv = append(argv, "-p", varName+`="$`+varName+`"`)
			}
		}
		rewritePlanRefs(planCopy, refs)
		deleteKey(st, "plan")
		setKey(st, "run", scalarNode(strings.Join(argv, " ")))
		pruneEmptyMappings(st)
		return st, nil
	}

	if ch := kit.MappingChild(st, "charly"); ch != nil && ch.Kind == yaml.SequenceNode {
		parts := []string{c.charlyBin, "-C", c.genDir}
		for _, a := range ch.Content {
			parts = append(parts, shellquote.ShellQuote(a.Value))
		}
		deleteKey(st, "charly")
		setKey(st, "run", scalarNode(strings.Join(parts, " ")))
	}
	return st, nil
}

// addTask registers a generated charly task for a lowered `plan:` step and returns its
// entity name.
func (c *lowerCtx) addTask(id string, plan *yaml.Node) string {
	name := fmt.Sprintf("_pipeline-%s-%s", c.name, entityIDSafe(id))
	taskBody := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	setKey(taskBody, "description", scalarNode(fmt.Sprintf("lowered from pipeline step %s/%s", c.name, id)))
	setKey(taskBody, "plan", plan)
	root := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	setKey(root, "task", taskBody)
	c.tasks = append(c.tasks, generatedTask{name: name, node: root})
	return name
}

// planRefs returns the distinct `$step.path` references in a plan, in document order.
func planRefs(plan *yaml.Node) []string {
	var out []string
	seen := map[string]bool{}
	walkScalarValues(plan, func(n *yaml.Node) {
		for _, m := range refRe.FindAllString(n.Value, -1) {
			if !seen[m] {
				seen[m] = true
				out = append(out, m)
			}
		}
	})
	return out
}

// rewritePlanRefs rewrites every `$step.path` in a plan to `${REF_<n>}`, the env var the
// lobster step sets (index i → REF_(i+1), matching planRefs' order). The BRACE form is
// mandatory: the expander that runs the plan (kit.ExpandOpVars, kit.TestVarRefPattern) is
// brace-only, so a bare `$REF_<n>` would reach a plugin-verb input as literal text.
func rewritePlanRefs(plan *yaml.Node, refs []string) {
	index := make(map[string]string, len(refs))
	for i, r := range refs {
		index[r] = fmt.Sprintf("${REF_%d}", i+1)
	}
	walkScalarValues(plan, func(n *yaml.Node) {
		n.Value = refRe.ReplaceAllStringFunc(n.Value, func(m string) string { return index[m] })
	})
}

// walkScalarValues calls fn on every scalar VALUE in a node subtree (mapping KEYS are
// never visited — a key is not a place a reference lives).
func walkScalarValues(n *yaml.Node, fn func(*yaml.Node)) {
	if n == nil {
		return
	}
	switch n.Kind {
	case yaml.SequenceNode:
		for _, c := range n.Content {
			walkScalarValues(c, fn)
		}
	case yaml.MappingNode:
		for i := 1; i < len(n.Content); i += 2 {
			walkScalarValues(n.Content[i], fn)
		}
	case yaml.ScalarNode:
		fn(n)
	}
}

// entityIDSafe makes a step id safe as a charly entity name.
func entityIDSafe(id string) string {
	var b strings.Builder
	for _, r := range id {
		switch {
		case (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' || r == '-':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	if b.Len() == 0 {
		return "step"
	}
	return b.String()
}

// pruneEmptyMappings drops keys whose value is an empty mapping. The generated structs
// carry value-struct fields (retry:, parallel:, input:) that yaml.v3 cannot omit — a
// zero struct marshals as `{}`, which is neither authored nor valid on reload.
func pruneEmptyMappings(st *yaml.Node) {
	out := make([]*yaml.Node, 0, len(st.Content))
	for i := 0; i+1 < len(st.Content); i += 2 {
		v := st.Content[i+1]
		if v.Kind == yaml.MappingNode && len(v.Content) == 0 {
			continue
		}
		out = append(out, st.Content[i], v)
	}
	st.Content = out
}

// --- small yaml.Node helpers (the ones kit does not already own) ---

func scalarNode(s string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: s}
}

func setKey(m *yaml.Node, key string, val *yaml.Node) {
	kit.SetMappingKey(m, key, val)
}

func deleteKey(m *yaml.Node, key string) {
	if m == nil || m.Kind != yaml.MappingNode {
		return
	}
	out := make([]*yaml.Node, 0, len(m.Content))
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			continue
		}
		out = append(out, m.Content[i], m.Content[i+1])
	}
	m.Content = out
}

func ensureMapping(m *yaml.Node, key string) *yaml.Node {
	if v := kit.MappingChild(m, key); v != nil && v.Kind == yaml.MappingNode {
		return v
	}
	v := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	setKey(m, key, v)
	return v
}

func marshalNode(v any) (*yaml.Node, error) {
	b, err := yaml.Marshal(v)
	if err != nil {
		return nil, err
	}
	var n yaml.Node
	if err := yaml.Unmarshal(b, &n); err != nil {
		return nil, err
	}
	if n.Kind == yaml.DocumentNode && len(n.Content) == 1 {
		return n.Content[0], nil
	}
	return &n, nil
}

func cloneNode(n *yaml.Node) (*yaml.Node, error) {
	b, err := yaml.Marshal(n)
	if err != nil {
		return nil, err
	}
	var out yaml.Node
	if err := yaml.Unmarshal(b, &out); err != nil {
		return nil, err
	}
	if out.Kind == yaml.DocumentNode && len(out.Content) == 1 {
		return out.Content[0], nil
	}
	return &out, nil
}
