// quadlet.go — the POD config-WRITE mechanism, relocated out of charly core
// (P11a). GenerateQuadlet + its pure closure render a systemd quadlet .container
// file from a QuadletConfig; the compiled-in candy/plugin-deploy-pod builds the
// QuadletConfig from the host config-resolve seam and calls this. A PURE render
// mechanism (M under the kernel/plugin boundary law): no host I/O, no globals —
// byte-identical to the former core generateQuadlet (S4 parity spike). VolumeMount
// is a resolved runtime type owned in this package (deploy_volume.go); the tunnel
// wire types are spec.TunnelConfig/TunnelPort (CUE-sourced, P11 wire-mandate repair);
// SecurityConfig is vmshared's; ResolvedSidecar is the host-adapted deploykit runtime
// type (defined below), not spec's wire ResolvedSidecar.
package deploykit

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/opencharly/sdk/kit"
	"github.com/opencharly/sdk/spec"
	"github.com/opencharly/sdk/vmshared"
)

// CollectedSecret is a fully resolved secret ready for provisioning + quadlet
// emission (the Secret= directive). Resolved runtime state (ruling C: the plugin
// builds it internally), not a wire type — owned here as a plain struct.
type CollectedSecret struct {
	Name           string // podman secret name: "charly-<image>-<name>"
	Target         string // container mount path
	Env            string // env var name INSIDE the container
	HostEnv        string // env var name on the HOST to read the value from
	SecretName     string // original secret name from the candy manifest
	Service        string // credential store service override
	Key            string // credential store key override
	RotateOnConfig bool   // bypass PodmanSecretExists short-circuit (rotate every config)
}

// ResolvedBindMount is a deploy-time resolved bind mount (host-path state).
// Runtime-only (never baked into an OCI label — LabelVolumeEntry is the label
// type), so it lives here as a plain deploykit struct (no CUE). Relocated from
// charly/enc.go with the P11 enc-model move.
type ResolvedBindMount struct {
	Name      string // e.g. "secrets"
	HostPath  string // effective host path (plain: expanded host, encrypted: plain dir)
	ContPath  string // container path (expanded)
	Encrypted bool   // for status/mount checks
}

// ResolvedSidecar is a fully-resolved sidecar ready for quadlet generation — the
// host-adapted form (the sidecar plugin's spec.ResolvedSidecar wire type is adapted
// on the host into these deploykit/vmshared runtime types). Resolved runtime state
// (ruling C), not a wire type, so it lives here as a plain struct beside the other
// pod config-write inputs. Consumed by the pod quadlet generators (generatePodQuadlet /
// generateSidecarQuadlet) that assemble the .pod + sidecar .container files.
type ResolvedSidecar struct {
	Name     string                  // sidecar key (e.g., "tailscale")
	Image    string                  // resolved OCI image ref
	Env      map[string]string       // merged env vars
	Secret   []CollectedSecret       // provisioned podman secrets
	Volume   []VolumeMount           // resolved named volumes
	Security vmshared.SecurityConfig // merged security config
}

// QuadletConfig holds the parameters for generating a quadlet .container file.
// An INTERNAL library type (ruling C): the plugin constructs + consumes it in
// one process (built from config-resolve data), so it never crosses the
// host↔plugin boundary and needs no CUE-sourcing.
type QuadletConfig struct {
	BoxName         string
	ImageRef        string
	Home            string
	Ports           []string
	Volumes         []VolumeMount
	BindMounts      []ResolvedBindMount
	GPU             bool
	BindAddress     string
	Tunnel          *spec.TunnelConfig
	UID             int
	GID             int
	Env             []string
	EnvFile         string
	Instance        string
	Security        vmshared.SecurityConfig
	Network         string
	Version         string
	Status          string
	Info            string
	Secrets         []CollectedSecret
	Entrypoint      []string
	CharlyBin       string
	EncryptedMounts bool
	KeyringBackend  bool
	PodName         string
	Sidecar         []ResolvedSidecar
}

// GenerateQuadlet produces the contents of a quadlet .container file. Pure.
func GenerateQuadlet(cfg QuadletConfig) string {
	name := kit.ContainerNameInstance(cfg.BoxName, cfg.Instance)
	var b strings.Builder

	fmt.Fprintf(&b, "# %s.container (generated by charly config)\n", name)
	if cfg.Version != "" {
		fmt.Fprintf(&b, "# Version: %s\n", cfg.Version)
	}
	status := cfg.Status
	if status == "" {
		status = "testing"
	}
	if status != "working" {
		fmt.Fprintf(&b, "# Status: %s\n", status)
		if cfg.Info != "" {
			fmt.Fprintf(&b, "# Info: %s\n", cfg.Info)
		}
	}
	emitUnitSection(&b, cfg)
	emitContainerSection(&b, cfg, name)
	emitServiceSection(&b, cfg)
	emitInstallSection(&b, cfg)
	return b.String()
}

func emitUnitSection(b *strings.Builder, cfg QuadletConfig) {
	b.WriteString("[Unit]\n")
	desc := cfg.BoxName
	if cfg.Instance != "" {
		desc = cfg.BoxName + " (" + cfg.Instance + ")"
	}
	fmt.Fprintf(b, "Description=OpenCharly %s\n", desc)
	b.WriteString("After=network-online.target\n")
	if cfg.Tunnel != nil && cfg.Tunnel.Provider == "cloudflare" {
		fmt.Fprintf(b, "Wants=%s\n", TunnelServiceFilename(cfg.BoxName))
	}
}

func emitContainerSection(b *strings.Builder, cfg QuadletConfig, name string) {
	b.WriteString("\n[Container]\n")
	if cfg.PodName != "" {
		fmt.Fprintf(b, "Pod=%s.pod\n", cfg.PodName)
	}
	fmt.Fprintf(b, "Image=%s\n", cfg.ImageRef)
	fmt.Fprintf(b, "ContainerName=%s\n", name)
	workDir := ResolveWorkingDir(cfg.Volumes, cfg.BindMounts, cfg.Home, cfg.BoxName, cfg.Instance)
	fmt.Fprintf(b, "WorkingDir=%s\n", workDir)
	if cfg.PodName == "" {
		if cfg.Network != "" {
			fmt.Fprintf(b, "Network=%s\n", cfg.Network)
		}
		for _, port := range cfg.Ports {
			fmt.Fprintf(b, "PublishPort=%s\n", LocalizePort(port, cfg.BindAddress))
		}
	}
	bindPaths := make(map[string]bool, len(cfg.BindMounts))
	for _, bm := range cfg.BindMounts {
		bindPaths[bm.ContPath] = true
	}
	for _, vol := range cfg.Volumes {
		if bindPaths[vol.ContainerPath] {
			continue
		}
		fmt.Fprintf(b, "Volume=%s:%s\n", vol.VolumeName, vol.ContainerPath)
	}
	for _, bm := range cfg.BindMounts {
		fmt.Fprintf(b, "Volume=%s:%s\n", bm.HostPath, bm.ContPath)
	}
	for _, m := range cfg.Security.Mounts {
		if after, ok := strings.CutPrefix(m, "tmpfs:"); ok {
			fmt.Fprintf(b, "Tmpfs=%s\n", after)
		} else {
			fmt.Fprintf(b, "Volume=%s\n", m)
		}
	}
	for _, s := range cfg.Secrets {
		if s.Env != "" {
			fmt.Fprintf(b, "Secret=%s,type=env,target=%s\n", s.Name, s.Env)
		} else {
			fmt.Fprintf(b, "Secret=%s,target=%s\n", s.Name, s.Target)
		}
	}
	emitContainerSecurity(b, cfg)
	if cfg.Security.CgroupNS != "" {
		fmt.Fprintf(b, "PodmanArgs=--cgroupns=%s\n", cfg.Security.CgroupNS)
	}
	for _, group := range cfg.Security.GroupAdd {
		fmt.Fprintf(b, "GroupAdd=%s\n", group)
	}
	if cfg.Security.IpcMode != "" {
		fmt.Fprintf(b, "PodmanArgs=--ipc=%s\n", cfg.Security.IpcMode)
	}
	if cfg.Security.ShmSize != "" && cfg.PodName == "" && !IpcModeBlocksShmSize(cfg.Security.IpcMode) {
		fmt.Fprintf(b, "ShmSize=%s\n", cfg.Security.ShmSize)
	}
	if len(cfg.BindMounts) > 0 {
		fmt.Fprintf(b, "UserNS=keep-id:uid=%d,gid=%d\n", cfg.UID, cfg.GID)
	}
	for _, e := range cfg.Env {
		if before, after, ok := strings.Cut(e, "="); ok {
			if strings.ContainsAny(after, `"{}[] `) {
				fmt.Fprintf(b, "Environment=%s=%q\n", before, after)
			} else {
				fmt.Fprintf(b, "Environment=%s\n", e)
			}
		} else {
			fmt.Fprintf(b, "Environment=%s\n", e)
		}
	}
	if cfg.EnvFile != "" {
		fmt.Fprintf(b, "EnvironmentFile=%s\n", cfg.EnvFile)
	}
	if len(cfg.Entrypoint) > 0 {
		fmt.Fprintf(b, "Exec=%s\n", strings.Join(cfg.Entrypoint, " "))
	} else {
		b.WriteString("Exec=sleep infinity\n")
	}
}

func emitContainerSecurity(b *strings.Builder, cfg QuadletConfig) {
	if cfg.GPU && !cfg.Security.Privileged {
		b.WriteString("AddDevice=nvidia.com/gpu=all\n")
	}
	if cfg.Security.Privileged {
		b.WriteString("SecurityLabelDisable=true\n")
		b.WriteString("PodmanArgs=--privileged\n")
		for _, opt := range cfg.Security.SecurityOpt {
			if opt != "label=disable" {
				fmt.Fprintf(b, "PodmanArgs=--security-opt %s\n", opt)
			}
		}
		for _, dev := range cfg.Security.Devices {
			fmt.Fprintf(b, "AddDevice=%s\n", dev)
		}
	} else {
		for _, cap := range cfg.Security.CapAdd {
			fmt.Fprintf(b, "AddCapability=%s\n", cap)
		}
		for _, dev := range cfg.Security.Devices {
			fmt.Fprintf(b, "AddDevice=%s\n", dev)
		}
		for _, opt := range cfg.Security.SecurityOpt {
			if opt == "label=disable" {
				b.WriteString("SecurityLabelDisable=true\n")
			} else {
				fmt.Fprintf(b, "PodmanArgs=--security-opt %s\n", opt)
			}
		}
	}
}

func emitServiceSection(b *strings.Builder, cfg QuadletConfig) {
	b.WriteString("\n[Service]\n")
	b.WriteString("Restart=always\n")
	if v := NormalizeCgroupSize(cfg.Security.MemoryMax); v != "" {
		fmt.Fprintf(b, "MemoryMax=%s\n", v)
	}
	if v := NormalizeCgroupSize(cfg.Security.MemoryHigh); v != "" {
		fmt.Fprintf(b, "MemoryHigh=%s\n", v)
	}
	if v := NormalizeCgroupSize(cfg.Security.MemorySwapMax); v != "" {
		fmt.Fprintf(b, "MemorySwapMax=%s\n", v)
	}
	if q := FormatCPUQuota(cfg.Security.Cpus); q != "" {
		fmt.Fprintf(b, "CPUQuota=%s\n", q)
	}
	if cfg.EncryptedMounts && cfg.CharlyBin != "" {
		imgArg := cfg.BoxName
		if cfg.Instance != "" {
			imgArg = cfg.BoxName + " -i " + cfg.Instance
		}
		fmt.Fprintf(b, "ExecStartPre=%s config mount %s\n", cfg.CharlyBin, imgArg)
		if cfg.KeyringBackend {
			b.WriteString("TimeoutStartSec=0\n")
		} else {
			b.WriteString("TimeoutStartSec=900\n")
		}
	} else {
		b.WriteString("TimeoutStartSec=900\n")
	}
	if cfg.Tunnel != nil && cfg.Tunnel.Provider == "tailscale" && len(cfg.Tunnel.Ports) > 0 {
		for _, tp := range cfg.Tunnel.Ports {
			port := fmt.Sprintf("%d", tp.Port)
			switch {
			case tp.Protocol == "udp":
				fmt.Fprintf(b, "# Port %s: UDP — not tunneled (tailscale serve does not support UDP; accessible directly between tailnet nodes)\n", port)
			case tp.Public:
				flag := TailscaleFlag(tp.Protocol)
				target := SchemeTarget(tp.Protocol, tp.Backend())
				fmt.Fprintf(b, "# Port %s: public (internet-accessible)\n", port)
				fmt.Fprintf(b, "ExecStartPost=tailscale funnel --bg %s=%s %s\n", flag, port, target)
			default:
				flag := TailscaleFlag(tp.Protocol)
				target := SchemeTarget(tp.Protocol, tp.Backend())
				proto := "https"
				if IsTCPFamily(tp.Protocol) {
					proto = "tcp"
				}
				fmt.Fprintf(b, "# Port %s: private (tailnet-only, %s)\n", port, proto)
				fmt.Fprintf(b, "ExecStartPost=tailscale serve --bg %s=%s %s\n", flag, port, target)
			}
		}
		for _, tp := range cfg.Tunnel.Ports {
			if tp.Protocol == "udp" {
				continue
			}
			port := fmt.Sprintf("%d", tp.Port)
			flag := TailscaleFlag(tp.Protocol)
			if tp.Public {
				fmt.Fprintf(b, "ExecStopPost=-tailscale funnel %s=%s off\n", flag, port)
			} else {
				fmt.Fprintf(b, "ExecStopPost=-tailscale serve %s=%s off\n", flag, port)
			}
		}
	}
}

func emitInstallSection(b *strings.Builder, cfg QuadletConfig) {
	b.WriteString("\n[Install]\n")
	if cfg.EncryptedMounts && !cfg.KeyringBackend {
		b.WriteString("# Encrypted volumes require 'charly start' (no keyring auto-unlock)\n")
	} else {
		b.WriteString("WantedBy=default.target\n")
	}
}

// ---- pure helpers (relocated from charly core; exported for the core aliases) ----

// ResolveWorkingDir returns the container working directory — the "workspace"
// volume/bind's container path if declared, else home.
func ResolveWorkingDir(volumes []VolumeMount, bindMounts []ResolvedBindMount, home, boxName, instance string) string {
	for _, v := range volumes {
		if kit.BareVolumeName(v.VolumeName, boxName, instance) == "workspace" {
			return v.ContainerPath
		}
	}
	for _, bm := range bindMounts {
		if bm.Name == "workspace" {
			return bm.ContPath
		}
	}
	return home
}

// LocalizePort applies a host bind address to a port mapping.
func LocalizePort(mapping string, bindAddr string) string {
	if p, ok := kit.ParsePortMapping(mapping); ok {
		out := p
		if out.BindAddr == "" {
			out.BindAddr = bindAddr
		}
		return kit.FormatPortMapping(out)
	}
	suffix := ""
	clean := mapping
	for _, proto := range []string{"/udp", "/tcp"} {
		if strings.HasSuffix(mapping, proto) {
			suffix = proto
			clean = strings.TrimSuffix(mapping, proto)
			break
		}
	}
	if strings.Contains(clean, ":") {
		return bindAddr + ":" + clean + suffix
	}
	return fmt.Sprintf("%s:%s:%s%s", bindAddr, clean, clean, suffix)
}

// IpcModeBlocksShmSize reports whether an IPC mode makes podman reject ShmSize.
func IpcModeBlocksShmSize(ipcMode string) bool { return ipcMode == "host" }

// SchemeTarget returns the backend URL for a tunnel scheme + port.
func SchemeTarget(scheme string, port int) string {
	switch scheme {
	case "tcp", "tls-terminated-tcp":
		return fmt.Sprintf("tcp://127.0.0.1:%d", port)
	default:
		return fmt.Sprintf("%s://127.0.0.1:%d", scheme, port)
	}
}

// TailscaleFlag returns the tailscale serve/funnel flag for a scheme.
func TailscaleFlag(scheme string) string {
	switch scheme {
	case "tcp":
		return "--tcp"
	case "tls-terminated-tcp":
		return "--tls-terminated-tcp"
	default:
		return "--https"
	}
}

// IsTCPFamily reports whether a scheme uses TCP-style forwarding.
func IsTCPFamily(scheme string) bool {
	switch scheme {
	case "tcp", "tls-terminated-tcp":
		return true
	default:
		return false
	}
}

// TunnelServiceFilename returns the systemd service filename for a cloudflare
// tunnel companion unit.
func TunnelServiceFilename(boxName string) string {
	return kit.ContainerName(boxName) + "-tunnel.service"
}

// NormalizeCgroupSize converts a podman-style size ("6g") to systemd's required
// uppercase suffix ("6G"); systemd silently rejects lowercase on Memory* caps.
func NormalizeCgroupSize(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	n := len(s)
	last := s[n-1]
	if last == 'K' || last == 'M' || last == 'G' || last == 'T' {
		return s
	}
	if last == 'k' || last == 'm' || last == 'g' || last == 't' {
		return s[:n-1] + strings.ToUpper(string(last))
	}
	return s
}

// FormatCPUQuota converts a podman --cpus value ("2.5") to systemd's CPUQuota
// percentage form ("250%"); empty/unparseable → "" (skip the directive).
func FormatCPUQuota(cpus string) string {
	cpus = strings.TrimSpace(cpus)
	if cpus == "" {
		return ""
	}
	f, err := strconv.ParseFloat(cpus, 64)
	if err != nil || f <= 0 {
		return ""
	}
	return fmt.Sprintf("%d%%", int(f*100+0.5))
}

// GenerateTunnelUnit produces the companion systemd .service unit for a cloudflare tunnel.
// Relocated from charly core with the P11 config-write move (the deploy:pod plugin writes it);
// cfgPath (the cloudflared config path) is passed in by the host — the resolution helper
// tunnelConfigPath stays core, so this generator is pure. Returns "" for a non-cloudflare (or
// nil) tunnel. Byte-identical to the former core generateTunnelUnit given the same cfgPath.
func GenerateTunnelUnit(cfg QuadletConfig, cfgPath string) string {
	if cfg.Tunnel == nil || cfg.Tunnel.Provider != "cloudflare" {
		return ""
	}
	name := kit.ContainerName(cfg.BoxName)
	tunnelName := cfg.Tunnel.TunnelName

	var b strings.Builder
	fmt.Fprintf(&b, "# %s-tunnel.service (generated by charly config)\n", name)
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=Cloudflare Tunnel for %s\n", name)
	fmt.Fprintf(&b, "BindsTo=%s.service\n", name)
	fmt.Fprintf(&b, "After=%s.service\n", name)

	b.WriteString("\n[Service]\n")
	fmt.Fprintf(&b, "ExecStart=cloudflared tunnel --config %s run %s\n", cfgPath, tunnelName)
	b.WriteString("Restart=always\n")

	b.WriteString("\n[Install]\n")
	b.WriteString("WantedBy=default.target\n")

	return b.String()
}
