package deploykit

import (
	"encoding/json"
	"sort"

	"github.com/opencharly/spec/spec"
)

// skills_collect.go — the box SKILL aggregator feeding the ai.opencharly.skills OCI label.
// A skill is a first-class `skill:` KIND entity (spec.Skill), co-located as a sibling top-level
// node in its owning candy's charly.yml and threaded into spec.Config.Skills (the raw
// uf.PluginKinds["skill"] map, mirroring the Config.Sidecar precedent). CollectSkills is a PURE
// walk producing the []spec.LabelSkillEntry the label carries — an image is SELF-DESCRIBING: its
// composed candies' skill definitions are readable directly via `charly box labels` /
// `charly bundle from-box`, with no external fetch (superseding the vestigial ai.opencharly.skill
// doc-pointer URL).
//
// Ownership: a skill's `owner` field names the candy that owns it. Only skills owned by a candy
// IN the composed chain (BoxCandyChain) ride the image's label — union-of-composed-only, which
// bounds the label size. Concept-candy skills (charly-core, charly-internals, candy/charly-hooks,
// …) are not image layers and never appear in any image's label; they live in the plugins/ corpus
// generated by candy/plugin-marketplace.
//
// Returns nil when the composition declares no skills.
func CollectSkills(cfg *spec.Config, layers map[string]CandyModel, boxName string) []spec.LabelSkillEntry {
	allCandyNames, _ := BoxCandyChain(cfg, layers, boxName)
	composed := make(map[string]bool, len(allCandyNames))
	for _, n := range allCandyNames {
		composed[n] = true
	}

	// Decode every authored skill body once; project the ones owned by a composed candy.
	// A body that fails to decode here is skipped (defensive only): the load path already
	// validated every authored body against the kind's served #SkillInput schema, so a
	// malformed body never reaches a built label.
	byKey := map[string]spec.LabelSkillEntry{}
	var order []string
	for _, raw := range cfg.Skills {
		if len(raw) == 0 {
			continue
		}
		var s spec.Skill
		if err := json.Unmarshal(raw, &s); err != nil {
			continue
		}
		if !composed[s.Owner] {
			continue
		}
		entry := projectSkill(s)
		key := entry.Family + "/" + entry.Name
		if _, dup := byKey[key]; dup {
			continue
		}
		byKey[key] = entry
		order = append(order, key)
	}
	if len(order) == 0 {
		return nil
	}
	sort.Strings(order)
	out := make([]spec.LabelSkillEntry, 0, len(order))
	for _, k := range order {
		out = append(out, byKey[k])
	}
	return out
}

// projectSkill maps the authored spec.Skill (the authoring kind shape) onto the wire
// spec.LabelSkillEntry (the label shape) — the authoring → wire projection.
func projectSkill(s spec.Skill) spec.LabelSkillEntry {
	refs := make([]spec.LabelSkillReference, 0, len(s.References))
	for _, r := range s.References {
		refs = append(refs, spec.LabelSkillReference(r)) // S1016 — convertible field-identical types
	}
	return spec.LabelSkillEntry{
		Family:      s.Family,
		Name:        s.Name,
		Owner:       s.Owner,
		Description: s.Description,
		Content:     s.Content,
		References:  refs,
		Triggers:    s.Triggers,
		Category:    s.Category,
	}
}
