package deploykit

import (
	"fmt"
	"strings"
)

// systemd_timer.go — the TIMER half of the non-quadlet supervision story: a systemd
// user `.timer` unit plus the ONESHOT service it activates.
//
// systemd_unit.go wraps a LONG-LIVED engine CLI (Type=simple, ExecStop). A scheduled
// job — a workflow run on a cron schedule, a periodic check — is the opposite shape:
// it starts, runs to completion, and exits (Type=oneshot), and there is nothing to
// stop. systemd expresses "run this on a schedule" as a .timer unit whose Unit=
// names the .service; the timer is what gets enabled under timers.target.
//
// This generator is pure TEXT: the schedule is an OnCalendar= expression the caller
// resolves (workflowkit.CronToOnCalendar turns the authored 5-field cron into one), so
// the deploy layer owns no cron grammar of its own (R3).

// TimerConfig describes a generated systemd user TIMER and the oneshot service it
// activates.
type TimerConfig struct {
	// Name is the timer basename; the activated service is Name + ".service".
	Name string
	// Description is the [Unit] Description of the timer.
	Description string
	// OnCalendar is a systemd OnCalendar= expression (e.g. "*-*-* 03:00:00"), from
	// workflowkit.CronToOnCalendar.
	OnCalendar string
	// Persistent makes systemd run a missed occurrence after downtime (the authored
	// `schedule.persistent`).
	Persistent bool
	// RandomizedDelaySec spreads simultaneous timers; optional.
	RandomizedDelaySec string
	// Service is the oneshot service the timer activates. Its Name defaults to the
	// timer's Name, its Type is forced to "oneshot", and its StopArgv/ExecStop is
	// suppressed — a run-to-completion job has no long-lived process to stop.
	Service SystemdUnitConfig
}

// TimerFilename returns the timer unit basename for a name.
func TimerFilename(name string) string { return name + ".timer" }

// GenerateSystemdTimer renders the systemd user .timer unit text for cfg. Returns ""
// when cfg has no OnCalendar (nothing to schedule).
func GenerateSystemdTimer(cfg TimerConfig) string {
	if cfg.OnCalendar == "" {
		return ""
	}
	name := cfg.Name
	desc := cfg.Description
	if desc == "" {
		desc = fmt.Sprintf("charly scheduled job %s", name)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s (generated by charly config)\n", TimerFilename(name))
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=%s\n", desc)

	b.WriteString("\n[Timer]\n")
	fmt.Fprintf(&b, "OnCalendar=%s\n", cfg.OnCalendar)
	if cfg.Persistent {
		b.WriteString("Persistent=true\n")
	}
	if cfg.RandomizedDelaySec != "" {
		fmt.Fprintf(&b, "RandomizedDelaySec=%s\n", cfg.RandomizedDelaySec)
	}
	fmt.Fprintf(&b, "Unit=%s\n", SystemdUnitFilename(name))

	b.WriteString("\n[Install]\n")
	b.WriteString("WantedBy=timers.target\n")
	return b.String()
}

// GenerateTimerService renders the ONESHOT service the timer activates: the same
// wrapper posture as GenerateSystemdUnit (foreground argv, systemd supervises it) but
// with Type=oneshot and no ExecStop — the job runs to completion and there is nothing
// to stop. Returns "" when cfg.Service has no StartArgv.
func GenerateTimerService(cfg TimerConfig) string {
	svc := cfg.Service
	if svc.Name == "" {
		svc.Name = cfg.Name
	}
	if svc.Description == "" {
		svc.Description = fmt.Sprintf("charly scheduled job %s (run to completion)", svc.Name)
	}
	svc.Type = "oneshot"
	svc.OmitStop = true
	return GenerateSystemdUnit(svc)
}
