package deploykit

import (
	"fmt"
	"sort"
	"strings"
)

// systemd_unit.go — the NON-QUADLET persistent-supervision unit generator.
//
// podman has a native systemd generator (quadlet): a `.container` file under
// ~/.config/containers/systemd/ that podman's generator turns into a service.
// nerdctl has NO such generator, so charly emits a plain systemd USER unit that
// wraps the nerdctl CLI directly — `ExecStart=/usr/bin/nerdctl run …` with an
// `ExecStop=/usr/bin/nerdctl stop <name>`. This is the spike-proven persistence
// path for nerdctl (a generated unit starts the container and `systemctl --user
// enable` links it for autostart).
//
// The unit is deliberately a thin wrapper: run lifecycle is nerdctl's, systemd
// only supervises the CLI process and restarts it on failure. The container is
// given `--rm` by the caller's argv, so a clean stop leaves no dead container.

// SystemdUnitConfig describes a generated systemd user unit wrapping an engine
// CLI. The caller supplies already-resolved argv (from BuildStartArgs or the
// provider's start_plan op), so this generator stays engine-agnostic: it is the
// unit WRAPPER, not an argv builder.
type SystemdUnitConfig struct {
	// Name is the deployment/container name (also the unit basename).
	Name string
	// Description is the [Unit] Description.
	Description string
	// StartArgv is the full argv for ExecStart (e.g. nerdctl run -d …).
	StartArgv []string
	// StopArgv is the argv for ExecStop (e.g. nerdctl stop <name>); optional.
	StopArgv []string
	// ExecStartPre holds optional argv run before start (e.g. `nerdctl rm -f <name>`).
	ExecStartPre [][]string
	// After / Wants are systemd ordering dependencies.
	After []string
	Wants []string
	// Restart is the systemd Restart= policy; defaults to on-failure.
	Restart string
	// WorkingDirectory is the [Service] WorkingDirectory=; optional.
	WorkingDirectory string
	// Environment holds KEY=VALUE pairs rendered as Environment= lines.
	Environment map[string]string
}

// SystemdUnitFilename returns the unit basename for a deployment name. The
// name is assumed already sanitized (kit.ContainerName) by the caller.
func SystemdUnitFilename(name string) string {
	return name + ".service"
}

// GenerateSystemdUnit renders the systemd user unit text for cfg. Returns "" when
// cfg has no StartArgv (nothing to run).
func GenerateSystemdUnit(cfg SystemdUnitConfig) string {
	if len(cfg.StartArgv) == 0 {
		return ""
	}
	name := cfg.Name
	desc := cfg.Description
	if desc == "" {
		desc = fmt.Sprintf("charly deployment %s (nerdctl-managed container)", name)
	}
	restart := cfg.Restart
	if restart == "" {
		restart = "on-failure"
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s (generated by charly config)\n", SystemdUnitFilename(name))
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=%s\n", desc)
	after := cfg.After
	if len(after) == 0 {
		after = []string{"network-online.target"}
	}
	fmt.Fprintf(&b, "After=%s\n", strings.Join(after, " "))
	wants := cfg.Wants
	if len(wants) == 0 {
		wants = []string{"network-online.target"}
	}
	fmt.Fprintf(&b, "Wants=%s\n", strings.Join(wants, " "))

	b.WriteString("\n[Service]\n")
	b.WriteString("Type=simple\n")
	for _, pre := range cfg.ExecStartPre {
		if len(pre) == 0 {
			continue
		}
		// The leading "-" makes a failure non-fatal (e.g. removing a container
		// that does not exist yet), matching the podman quadlet posture.
		fmt.Fprintf(&b, "ExecStartPre=-%s\n", systemdEscapeArgv(pre))
	}
	fmt.Fprintf(&b, "ExecStart=%s\n", systemdEscapeArgv(cfg.StartArgv))
	if len(cfg.StopArgv) > 0 {
		fmt.Fprintf(&b, "ExecStop=%s\n", systemdEscapeArgv(cfg.StopArgv))
	}
	// Deterministic order: a Go map range is non-deterministic, so the same config
	// would emit different units across runs (defeating any drift gate). Sort keys.
	for _, k := range sortedKeys(cfg.Environment) {
		fmt.Fprintf(&b, "Environment=%s\n", systemdQuote(k+"="+cfg.Environment[k]))
	}
	if cfg.WorkingDirectory != "" {
		fmt.Fprintf(&b, "WorkingDirectory=%s\n", cfg.WorkingDirectory)
	}
	fmt.Fprintf(&b, "Restart=%s\n", restart)
	b.WriteString("RestartSec=3\n")

	b.WriteString("\n[Install]\n")
	b.WriteString("WantedBy=default.target\n")
	return b.String()
}

// systemdEscapeArgv renders an argv into a single systemd Exec line. Arguments
// containing whitespace or shell-special characters are double-quoted with
// systemd's backslash escaping (systemd does NOT run a shell; it splits the
// line itself, so naive joining would break an arg such as
// `--userns=keep-id:uid=1000,gid=1000` or an env value with spaces).
func systemdEscapeArgv(argv []string) string {
	parts := make([]string, 0, len(argv))
	for _, a := range argv {
		parts = append(parts, systemdEscapeArg(a))
	}
	return strings.Join(parts, " ")
}

// systemdEscapeArg quotes ONE argument when it needs it. Safe characters pass
// through unquoted so generated units stay readable.
//
// SYSTEMD SPECIFIERS: `%` is expanded by systemd even inside quotes (`%i`, `%n`,
// …), so a LITERAL percent must be doubled to `%%`. systemdQuote applies that
// doubling in EVERY path (quoted or not) — a `%` is never passed through raw.
func systemdEscapeArg(a string) string {
	return systemdQuote(a)
}

// systemdQuote renders one systemd field value: it doubles any literal `%`
// (systemd specifier escaping) and double-quotes with backslash escaping when
// the value contains whitespace or a systemd-special character. Order matters —
// the `%`→`%%` doubling is applied to the RAW value first, then quoting, so a
// value that needs quoting still gets its `%` doubled inside the quotes.
func systemdQuote(a string) string {
	// Escape the systemd specifier prefix first — this is required whether or not
	// the value ends up quoted.
	a = strings.ReplaceAll(a, "%", "%%")
	if a != "" && !strings.ContainsAny(a, " \t\n\"'\\$&*()[]{};<>|`~?!#") {
		return a
	}
	// Double-quote and escape the characters systemd treats specially inside quotes.
	r := strings.NewReplacer("\\", "\\\\", "\"", "\\\"")
	return "\"" + r.Replace(a) + "\""
}

// sortedKeys returns a map's keys in sorted order, so a rendered unit is
// deterministic across runs.
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
