package deploykit

import (
	"strings"
	"testing"
)

func TestGenerateSystemdUnit_WrapsNerdctlArgv(t *testing.T) {
	cfg := SystemdUnitConfig{
		Name:        "my-app",
		Description: "my-app (nerdctl)",
		StartArgv:   []string{"nerdctl", "run", "--rm", "--name", "my-app", "--userns", "host", "img:latest"},
		StopArgv:    []string{"nerdctl", "stop", "my-app"},
		ExecStartPre: [][]string{
			{"nerdctl", "rm", "-f", "my-app"},
		},
		Environment: map[string]string{"FOO": "bar"},
	}
	got := GenerateSystemdUnit(cfg)

	for _, want := range []string{
		"# my-app.service (generated by charly config)",
		"[Unit]",
		"[Service]",
		"[Install]",
		"ExecStart=nerdctl run --rm --name my-app --userns host img:latest",
		"ExecStop=nerdctl stop my-app",
		"ExecStartPre=-nerdctl rm -f my-app",
		"Restart=on-failure",
		"WantedBy=default.target",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("generated unit missing %q:\n%s", want, got)
		}
	}
}

func TestGenerateSystemdUnit_QuotesArgsWithSpaces(t *testing.T) {
	cfg := SystemdUnitConfig{
		Name:      "svc",
		StartArgv: []string{"nerdctl", "run", "-e", "MSG=hello world", "img"},
	}
	got := GenerateSystemdUnit(cfg)
	if !strings.Contains(got, `ExecStart=nerdctl run -e "MSG=hello world" img`) {
		t.Errorf("an arg with a space must be quoted:\n%s", got)
	}
}

func TestGenerateSystemdUnit_EmptyStartArgvRendersNothing(t *testing.T) {
	if got := GenerateSystemdUnit(SystemdUnitConfig{Name: "x"}); got != "" {
		t.Errorf("empty StartArgv must render nothing, got:\n%s", got)
	}
}

func TestSystemdUnitFilename(t *testing.T) {
	if got := SystemdUnitFilename("my-app"); got != "my-app.service" {
		t.Errorf("SystemdUnitFilename = %q, want my-app.service", got)
	}
}

// TestBuildStartArgs_NerdctlSharesViaWorkloadUser is the behavioural gate for the
// uid-sharing fix: with no keep-id, the engine must launch the workload as the
// configured WorkloadUser (container-uid 0 == host user rootless) instead of a
// keep-id flag it does not have.
func TestBuildStartArgs_NerdctlSharesViaWorkloadUser(t *testing.T) {
	bind := []ResolvedBindMount{{HostPath: "/home/u/data", ContPath: "/data"}}
	args := BuildStartArgs(
		"nerdctl", "img:latest", 1000, 1000, nil, "svc",
		nil, bind, false, "127.0.0.1", nil, SecurityConfig{}, []string{"sleep", "infinity"}, "/work",
	)
	joined := strings.Join(args, " ")
	if !strings.Contains(joined, "--user 0") {
		t.Errorf("nerdctl bind-mount start args must set --user 0 for host-identical sharing, got: %s", joined)
	}
	if strings.Contains(joined, "--userns=keep-id") {
		t.Errorf("nerdctl has no keep-id; it must not be emitted: %s", joined)
	}
	if args[0] != "nerdctl" {
		t.Errorf("argv[0] = %q, want nerdctl", args[0])
	}
}

// TestBuildStartArgs_PodmanKeepsKeepID is the regression gate: podman's existing
// keep-id behaviour must be unchanged.
func TestBuildStartArgs_PodmanKeepsKeepID(t *testing.T) {
	bind := []ResolvedBindMount{{HostPath: "/home/u/data", ContPath: "/data"}}
	args := BuildStartArgs(
		"podman", "img:latest", 1000, 1000, nil, "svc",
		nil, bind, false, "127.0.0.1", nil, SecurityConfig{}, []string{"sleep", "infinity"}, "/work",
	)
	joined := strings.Join(args, " ")
	if !strings.Contains(joined, "--userns=keep-id:uid=1000,gid=1000") {
		t.Errorf("podman bind-mount start args must keep keep-id, got: %s", joined)
	}
	if strings.Contains(joined, "--user 0") {
		t.Errorf("podman must not fall back to --user 0: %s", joined)
	}
}

// TestGenerateSystemdUnit_DeterministicEnvOrder is the regression gate for the
// map-iteration defect: the same multi-entry Environment must render identically
// across runs (sorted keys), not in Go's randomized map order.
func TestGenerateSystemdUnit_DeterministicEnvOrder(t *testing.T) {
	cfg := SystemdUnitConfig{
		Name:      "svc",
		StartArgv: []string{"nerdctl", "run", "img"},
		Environment: map[string]string{
			"ZED": "1", "ALPHA": "2", "MID": "3", "BETA": "4", "YANKEE": "5",
		},
	}
	first := GenerateSystemdUnit(cfg)
	for i := 0; i < 20; i++ {
		if got := GenerateSystemdUnit(cfg); got != first {
			t.Fatalf("Environment order is non-deterministic across runs:\nfirst=%s\nnow=%s", first, got)
		}
	}
	// And the order is the SORTED one.
	want := "Environment=ALPHA=2\nEnvironment=BETA=4\nEnvironment=MID=3\nEnvironment=YANKEE=5\nEnvironment=ZED=1\n"
	if !strings.Contains(first, want) {
		t.Errorf("Environment lines must be sorted:\n%s", first)
	}
}

// TestGenerateSystemdUnit_EscapesSystemdSpecifier is the regression gate for the
// % escaping defect: a literal percent must be emitted as %%, everywhere (an
// ExecStart arg AND an Environment value), because systemd expands % specifiers
// even inside quotes.
func TestGenerateSystemdUnit_EscapesSystemdSpecifier(t *testing.T) {
	cfg := SystemdUnitConfig{
		Name:        "svc",
		StartArgv:   []string{"nerdctl", "run", "-e", "PCT=100%done", "img"},
		Environment: map[string]string{"LOG": "50%"},
	}
	got := GenerateSystemdUnit(cfg)
	if strings.Contains(got, "100%done") || strings.Contains(got, "LOG=50%\n") {
		t.Errorf("a literal %% must be doubled for systemd:\n%s", got)
	}
	if !strings.Contains(got, "100%%done") {
		t.Errorf("argv %% not doubled:\n%s", got)
	}
	if !strings.Contains(got, "Environment=LOG=50%%") {
		t.Errorf("env %% not doubled:\n%s", got)
	}
}

// TestBuildStartArgs_NerdctlDropsRemoveWithDetach is the live-found gate: nerdctl
// REJECTS `-d --rm` ("flags -d and --rm cannot be specified together"), so the
// detached argv must NOT carry --rm for nerdctl; podman/docker must keep it.
func TestBuildStartArgs_NerdctlDropsRemoveWithDetach(t *testing.T) {
	nerd := strings.Join(BuildStartArgs("nerdctl", "img:latest", 1000, 1000, nil, "svc", nil, nil, false, "127.0.0.1", nil, SecurityConfig{}, []string{"sleep", "infinity"}, "/work"), " ")
	if strings.Contains(nerd, "--rm") {
		t.Errorf("nerdctl rejects -d --rm; the detached argv must drop --rm: %s", nerd)
	}
	if !strings.HasPrefix(nerd, "nerdctl run -d --name svc") {
		t.Errorf("nerdctl argv shape unexpected: %s", nerd)
	}
	pod := strings.Join(BuildStartArgs("podman", "img:latest", 1000, 1000, nil, "svc", nil, nil, false, "127.0.0.1", nil, SecurityConfig{}, []string{"sleep", "infinity"}, "/work"), " ")
	if !strings.Contains(pod, "--rm") {
		t.Errorf("podman accepts -d --rm; it must keep --rm: %s", pod)
	}
}

// TestBuildForegroundRunArgs_NoDetach_WithRemove pins the unit's ExecStart argv
// contract: BuildForegroundRunArgs emits NO `-d` and DOES emit `--rm` (foreground
// --rm is always legal, including nerdctl, where `-d --rm` is rejected).
func TestBuildForegroundRunArgs_NoDetach_WithRemove(t *testing.T) {
	for _, engine := range []string{"podman", "docker", "nerdctl"} {
		joined := strings.Join(BuildForegroundRunArgs(engine, "img:latest", 1000, 1000, nil, "svc", nil, nil, false, "127.0.0.1", nil, SecurityConfig{}, []string{"sleep", "infinity"}, "/work"), " ")
		if strings.Contains(joined, " -d ") {
			t.Errorf("%s foreground argv must NOT detach: %s", engine, joined)
		}
		if !strings.Contains(joined, " --rm ") {
			t.Errorf("%s foreground argv must keep --rm: %s", engine, joined)
		}
		if !strings.HasPrefix(joined, engine+" run --rm --name svc") {
			t.Errorf("%s foreground argv shape unexpected: %s", engine, joined)
		}
	}
}
