package deploykit

import (
	"strings"
	"testing"
)

func TestGenerateSystemdUnit_WrapsNerdctlArgv(t *testing.T) {
	cfg := SystemdUnitConfig{
		Name:        "my-app",
		Description: "my-app (nerdctl)",
		StartArgv:   []string{"nerdctl", "run", "-d", "--rm", "--name", "my-app", "--userns", "host", "img:latest"},
		StopArgv:    []string{"nerdctl", "stop", "my-app"},
		ExecStartPre: [][]string{
			{"nerdctl", "rm", "-f", "my-app"},
		},
		Environment: map[string]string{"FOO": "bar"},
	}
	got := GenerateSystemdUnit(cfg)

	for _, want := range []string{
		"# my-app.service (generated by charly config)",
		"[Unit]",
		"[Service]",
		"[Install]",
		"ExecStart=nerdctl run -d --rm --name my-app --userns host img:latest",
		"ExecStop=nerdctl stop my-app",
		"ExecStartPre=-nerdctl rm -f my-app",
		"Restart=on-failure",
		"WantedBy=default.target",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("generated unit missing %q:\n%s", want, got)
		}
	}
}

func TestGenerateSystemdUnit_QuotesArgsWithSpaces(t *testing.T) {
	cfg := SystemdUnitConfig{
		Name:      "svc",
		StartArgv: []string{"nerdctl", "run", "-e", "MSG=hello world", "img"},
	}
	got := GenerateSystemdUnit(cfg)
	if !strings.Contains(got, `ExecStart=nerdctl run -e "MSG=hello world" img`) {
		t.Errorf("an arg with a space must be quoted:\n%s", got)
	}
}

func TestGenerateSystemdUnit_EmptyStartArgvRendersNothing(t *testing.T) {
	if got := GenerateSystemdUnit(SystemdUnitConfig{Name: "x"}); got != "" {
		t.Errorf("empty StartArgv must render nothing, got:\n%s", got)
	}
}

func TestSystemdUnitFilename(t *testing.T) {
	if got := SystemdUnitFilename("my-app"); got != "my-app.service" {
		t.Errorf("SystemdUnitFilename = %q, want my-app.service", got)
	}
}

// TestBuildStartArgs_NerdctlSharesViaWorkloadUser is the behavioural gate for the
// uid-sharing fix: with no keep-id, the engine must launch the workload as the
// configured WorkloadUser (container-uid 0 == host user rootless) instead of a
// keep-id flag it does not have.
func TestBuildStartArgs_NerdctlSharesViaWorkloadUser(t *testing.T) {
	bind := []ResolvedBindMount{{HostPath: "/home/u/data", ContPath: "/data"}}
	args := BuildStartArgs(
		"nerdctl", "img:latest", 1000, 1000, nil, "svc",
		nil, bind, false, "127.0.0.1", nil, SecurityConfig{}, []string{"sleep", "infinity"}, "/work",
	)
	joined := strings.Join(args, " ")
	if !strings.Contains(joined, "--user 0") {
		t.Errorf("nerdctl bind-mount start args must set --user 0 for host-identical sharing, got: %s", joined)
	}
	if strings.Contains(joined, "--userns=keep-id") {
		t.Errorf("nerdctl has no keep-id; it must not be emitted: %s", joined)
	}
	if args[0] != "nerdctl" {
		t.Errorf("argv[0] = %q, want nerdctl", args[0])
	}
}

// TestBuildStartArgs_PodmanKeepsKeepID is the regression gate: podman's existing
// keep-id behaviour must be unchanged.
func TestBuildStartArgs_PodmanKeepsKeepID(t *testing.T) {
	bind := []ResolvedBindMount{{HostPath: "/home/u/data", ContPath: "/data"}}
	args := BuildStartArgs(
		"podman", "img:latest", 1000, 1000, nil, "svc",
		nil, bind, false, "127.0.0.1", nil, SecurityConfig{}, []string{"sleep", "infinity"}, "/work",
	)
	joined := strings.Join(args, " ")
	if !strings.Contains(joined, "--userns=keep-id:uid=1000,gid=1000") {
		t.Errorf("podman bind-mount start args must keep keep-id, got: %s", joined)
	}
	if strings.Contains(joined, "--user 0") {
		t.Errorf("podman must not fall back to --user 0: %s", joined)
	}
}
