package deploykit

// vm_box_emit.go — the VM box image emitter + reader (cutover plan task 2, the VM
// analog of the pod-side WriteLabels / CapabilitiesFromLabels pair). A VM box is an
// OCI image whose labels carry the VM metadata contract and whose layer carries the
// disk artifact: the disk COPY is the layer, the labels are the contract.
//
// The metadata contract is spec.VmBoxMetadata riding ONE whole-struct JSON label —
// spec.LabelVmBox (ai.opencharly.vm.box), the VM analog of the per-field
// ai.opencharly.* family the pod side names via CapabilityLabelMap. The completeness
// gate lives spec-side (spec.VmBoxLabelMap + spec.CheckVmBoxLabelCompleteness, spec PR
// #90) and is exercised from TestVmBoxLabelCompleteness here so the sdk build breaks
// when a field is added without a label mapping.
//
// EmitVmBox (write side): scratch image, single COPY of the disk artifact to
// /disk.qcow2, plus ai.opencharly.version (the box CalVer) and ai.opencharly.description
// (JSON-encoded, like every JSON label the pod emitter writes) for human inspection.
// VmCapabilitiesFromLabels (read side): engine inspect → the ai.opencharly.vm.box
// label → unmarshal, the VM analog of CapabilitiesFromLabels' ExtractMetadata path.

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/opencharly/spec/container"
	"github.com/opencharly/spec/shellquote"
	"github.com/opencharly/spec/spec"
)

// EmitVmBox builds a VM box image in the local engine's storage from a materialized
// disk artifact + the VM metadata contract: a scratch image whose labels carry
// spec.VmBoxMetadata (whole-struct JSON on spec.LabelVmBox, plus version + description
// for inspect-ability) and whose single layer carries the disk at /disk.qcow2.
//
// The build context is the disk's own parent directory and the Containerfile is staged
// in a temp dir (passed via -f): the disk is never copied, buildah streams the file
// into the layer directly. The temp Containerfile is removed on return.
func EmitVmBox(engine, ref string, meta *spec.VmBoxMetadata, diskPath string) error {
	if meta == nil {
		return fmt.Errorf("EmitVmBox: nil metadata")
	}
	absDisk, err := filepath.Abs(diskPath)
	if err != nil {
		return fmt.Errorf("EmitVmBox: resolving disk path %q: %w", diskPath, err)
	}
	if _, err := os.Stat(absDisk); err != nil {
		return fmt.Errorf("EmitVmBox: disk %q: %w", absDisk, err)
	}

	metaJSON, err := json.Marshal(meta)
	if err != nil {
		return fmt.Errorf("EmitVmBox: marshaling VmBoxMetadata: %w", err)
	}

	dir, err := os.MkdirTemp("", "vm-box-emit-*")
	if err != nil {
		return fmt.Errorf("EmitVmBox: staging Containerfile: %w", err)
	}
	defer func() { _ = os.RemoveAll(dir) }()

	var cf strings.Builder
	cf.WriteString("# VM box image - generated by deploykit.EmitVmBox (do not edit)\n")
	cf.WriteString("FROM scratch\n")
	// The disk COPY is the artifact layer. Double-quote the source only when the
	// basename needs it (Dockerfile COPY strips matching double quotes).
	fmt.Fprintf(&cf, "COPY %s /disk.qcow2\n", copyQuote(filepath.Base(absDisk)))
	// The labels are the contract. ai.opencharly.vm.box always; version and
	// description are conditional (omitted when empty), mirroring WriteLabels.
	fmt.Fprintf(&cf, "LABEL %s=%s\n", spec.LabelVmBox, shellquote.ShellQuote(string(metaJSON)))
	if meta.Version != "" {
		fmt.Fprintf(&cf, "LABEL %s=%s\n", spec.LabelVersion, shellquote.ShellQuote(meta.Version))
	}
	if meta.Description != "" {
		descJSON, _ := json.Marshal(meta.Description)
		fmt.Fprintf(&cf, "LABEL %s=%s\n", spec.LabelDescription, shellquote.ShellQuote(string(descJSON)))
	}

	cfPath := filepath.Join(dir, "Containerfile")
	if err := os.WriteFile(cfPath, []byte(cf.String()), 0o644); err != nil {
		return fmt.Errorf("EmitVmBox: writing Containerfile: %w", err)
	}

	binary := container.EngineBinary(engine)
	build := exec.Command(binary, "build", "-t", ref, "-f", cfPath, filepath.Dir(absDisk))
	out, err := build.CombinedOutput()
	if err != nil {
		msg := strings.TrimSpace(string(out))
		if msg == "" {
			msg = err.Error()
		}
		return fmt.Errorf("EmitVmBox: %s build -t %s: %w: %s", binary, ref, err, msg)
	}
	return nil
}

// VmCapabilitiesFromLabels reads the VM metadata contract back from a VM box image in
// local engine storage: engine inspect → the ai.opencharly.vm.box label → unmarshal
// into *spec.VmBoxMetadata. The VM analog of CapabilitiesFromLabels (deploykit); the
// source-less VM deploy (`charly fleet from-box vm:<ref>`) reconstructs every field from
// the pushed box image via this function.
func VmCapabilitiesFromLabels(engine, imageRef string) (*spec.VmBoxMetadata, error) {
	labels, err := container.InspectLabels(engine, imageRef)
	if err != nil {
		if !container.LocalImageExists(engine, imageRef) {
			return nil, fmt.Errorf("%w: %s", spec.ErrImageNotLocal, imageRef)
		}
		return nil, err
	}
	raw := labels[spec.LabelVmBox]
	if raw == "" {
		return nil, fmt.Errorf("image %q has no %s label (not a VM box image?)", imageRef, spec.LabelVmBox)
	}
	var meta spec.VmBoxMetadata
	if err := json.Unmarshal([]byte(raw), &meta); err != nil {
		return nil, fmt.Errorf("parsing %s from %s: %w", spec.LabelVmBox, imageRef, err)
	}
	return &meta, nil
}

// copyQuote wraps a COPY source in double quotes when its basename contains whitespace
// (the only case the Dockerfile parser requires quoting); plain names stay bare.
func copyQuote(name string) string {
	if strings.ContainsAny(name, " \t") {
		return "\"" + strings.ReplaceAll(name, "\"", "\\\"") + "\""
	}
	return name
}
